### ISSUE TITLE
Cannot import lib.netpros

### ISSUE THREAD

**Issue by ZenHarbinger** [arleilps/sparse-wavelets#1]
It appears that a netpros.py file is possibly missing from the 'lib' directory.
```
Traceback (most recent call last):
  File "compression-experiments.py", line 31, in <module>
    from lib.experiments import *
  File "/home/matta/src/sparse-wavelets/lib/experiments.py", line 3, in <module>
    from lib.netpros import *
ImportError: No module named netpros
```

**Comment by ZenHarbinger** [comment]
Thanks for updating the scripts.
